name: Marty
favicon: null
layout_spectrum: 0.11509989504702389
typography_spectrum: 0.8656483176164329
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.8895923828240484
  lightness: 0.7370097790844738
  saturation: 0.9642447477672249
  rhythmicContrast: 0.40448225336149335
purpose: []
