name: Marty
favicon: null
layout_spectrum: 0.11509989504702389
typography_spectrum: 0.8656483176164329
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#33359c'
    - '#f8a600'
    - '#8788c4'
    - '#ddddee'
  brandStrength: 0.875
  lightness: 0.75
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
